name: appavanzada
description: "Gestor de Tareas - AplicaciÃ³n avanzada para organizar proyectos y subtareas."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0


  # Persistencia de datos
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.9.0
  intl: ^0.20.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.10.4

flutter:
  uses-material-design: true

